SET SERVEROUTPUT ON;
SET VERIFY OFF;
CREATE OR REPLACE PACKAGE MYPACK AS

	FUNCTION F1(A1 IN NUMBER) RETURN NUMBER;
	
	PROCEDURE P1(B1 IN NUMBER);

END MYPACK;
/

CREATE OR REPLACE PACKAGE BODY MYPACK AS

	FUNCTION F1(A1 IN NUMBER) RETURN NUMBER IS
	
	BEGIN
		IF MOD(A1,2) = 0 THEN
			RETURN 1;
		ELSE
			RETURN 0;
		END IF;
	END F1;
	
	PROCEDURE P1(B1 IN NUMBER) IS
	
	BEGIN
		IF MOD(B1,2) = 0 THEN
			DBMS_OUTPUT.PUT_LINE('EVEN');
		ELSE
			DBMS_OUTPUT.PUT_LINE('ODD');
		END IF;
	END P1;
END MYPACK;
/

-- SELECT MYPACK.F1(20) FORM DUAL;
-- EXEC MYPACK.P1(31);

DECLARE
	D NUMBER;
	 
BEGIN
	D := MYPACK.F1(113);
	DBMS_OUTPUT.PUT_LINE(D);
	MYPACK.P1(205);
END;
/