SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE MyFirstProcedure IS

BEGIN
	DBMS_OUTPUT.PUT_LINE('HELLO, THIS IS PROCEDURE');
END MyFirstProcedure;
/

--WAY-01 [ USING EXEC KEYWORD]
EXEC MyFirstProcedure;

-- WAY-02 [USIND BEGIN-END BLOCK]
BEGIN
	MyFirstProcedure;
END;
/
--WAY-03 [CALLING FROM ANOTHER FILE]
-- CHECK 'CALL PROCEDURE.SQL'


